/**
 * Server-rendered markup: sidebar, views, modals.
 *
 * Extracted verbatim from the single dashboard.ts template; see
 * test/dashboard_snapshot.test.mjs for the byte-exact contract.
 */
export const DASHBOARD_MARKUP = `<main class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">◇</div><div>OpenCodex<small>控制中心</small></div></div><nav class="nav"><button class="active" data-view="gateway"><span class="ico">◎</span>网关</button><button data-view="logs"><span class="ico">☷</span>日志</button></nav><button id="language-toggle" class="language-toggle" type="button">English</button><div class="side-spacer"></div><div class="app-safety"><button data-view="settings"><span class="ico">⚙</span><span><strong>应用与安全</strong><span>重启 · 诊断 · 高级设置</span></span><span>›</span></button></div></aside>
<section class="workspace"><section id="view-gateway" class="view active"><div class="shield"><div class="shield-icon">★</div><div><b>原生 Codex 受保护</b><span>网关仅改变待应用的第三方模型；原生 Codex、Computer Use 与 MCP 保持原样。</span></div></div><div class="headline"><div><h1>网关</h1><p>保存服务商，再管理待应用的第三方模型</p></div></div><div class="gateway-grid"><article class="card gateway-card"><div class="card-head"><h2>API Key 接入</h2><span class="pill">仅填写 API Key</span></div><p class="help">地址与模型名已预设。保存后加入下方待应用清单，不会自动重启 Codex。</p><div id="api-provider-list" class="provider-list"><div class="empty">正在读取接入模板…</div></div></article></div><article class="card enabled-panel"><div class="card-head"><div><h2>待应用模型</h2><p class="help">保存 Key 后模型先加入此处；可逐个测试或删除，重启 Codex 后才在 Desktop 生效。</p></div><button id="restart-button" class="button" disabled title="添加至少一个第三方模型后才可重启">↻ 重启 Codex（应用模型菜单）</button></div><div id="enabled-models" class="enabled-list"><div class="empty">正在读取待应用模型…</div></div></article></section>



<section id="view-logs" class="view"><div class="headline"><div><h1>日志</h1><p>网关与本机控制中心的运行记录；敏感凭据不会出现在这里。</p></div><button id="refresh-logs" class="button">刷新</button></div><article class="card gateway-card"><div id="log-list" class="log-list"><div class="empty">正在读取日志…</div></div></article></section>

<section id="view-settings" class="view"><div class="headline"><div><h1>应用与安全</h1><p>重启与恢复原生模式集中放在这里。</p></div></div><div class="panel-grid"><article class="card gateway-card"><div class="card-head"><h2>应用操作</h2></div><div class="settings-stack"><div class="setting"><div><b>重启 Codex</b><span>仅在已启用模型后，用于刷新 Desktop 的模型菜单。</span></div><button id="restart-settings" class="button">重启 Codex</button></div><div class="setting"><div><b>恢复原生 Codex</b><span>移除第三方网关和模型目录，不改动 Computer Use / MCP。</span></div><button id="reset-button" class="button danger">还原原生</button></div></div></article></div></section></section></main>

<div id="provider-modal" class="modal"><form id="provider-form" class="modal-box"><h2 id="provider-modal-title">配置服务商</h2><p id="provider-modal-copy">预设地址与模型将自动使用。保存 Key 后模型会加入待应用清单，可在下方测试、保留或删除；重启 Codex 后才正式生效。</p><div class="form-grid"><label class="field wide">API Key<input id="provider-key" type="password" autocomplete="off" placeholder="保存后写入 macOS Keychain" required></label></div><div id="candidate-note" class="note hidden"></div><div class="modal-actions"><button type="button" id="close-modal" class="button">取消</button><button id="test-candidate" class="button primary" type="submit">保存并添加模型</button><button id="confirm-enable" class="button primary hidden" type="button">保存并添加模型</button></div></div><div id="toast" class="toast"></div>`;
