/**
 * Server-rendered markup for the control centre.
 *
 * The page has one job — configure providers and models — so it is a single
 * scrolling document rather than a navigable app. The two app-level actions
 * live in the top bar; logs are a section, not a destination.
 *
 * Element ids are the contract with app.ts; renaming one silently breaks a
 * handler. test/dashboard_snapshot.test.mjs pins the rendered output.
 */
export const DASHBOARD_MARKUP = `<main class="app">
<header class="topbar"><div class="brand"><div class="brand-logo-wrap"><img class="brand-logo" src="/assets/opencodex-logo-compact.png?v=3" alt="OpenCodex 标志"></div><div>OpenCodex<small>本地控制中心</small></div></div><div class="topbar-actions"><button id="language-toggle" class="button ghost" type="button">English</button><button id="restart-settings" class="button">重启 Codex</button><button id="disengage-button" class="button danger" title="立即让 Codex 脱离 OpenCodex：注销 CODEX_CLI_PATH、移除托管配置并重启 Desktop。服务商、API Key 和模型全部保留，重新启动网关即可恢复。">脱离 OpenCodex</button></div></header>
<section class="workspace">
<section class="panel"><div class="headline"><div><h1>服务商与模型</h1><p>填入 API Key 添加模型；重启 Codex 后才在 Desktop 的模型菜单里生效。</p></div></div><article class="card gateway-card"><div class="card-head"><h2>API Key 接入</h2><span class="pill">仅填写 API Key</span></div><p class="help">地址与模型名已预设。保存后加入下方待应用清单，不会自动重启 Codex。</p><div id="api-provider-list" class="provider-list"><div class="empty">正在读取接入模板…</div></div></article><article class="card enabled-panel"><div class="card-head"><div><h2>待应用模型</h2><p class="help">保存 Key 后模型先加入此处；可逐个测试或删除，重启 Codex 后才在 Desktop 生效。</p></div><button id="restart-button" class="button" disabled title="添加至少一个第三方模型后才可重启">↻ 重启 Codex（应用模型菜单）</button></div><div id="enabled-models" class="enabled-list"><div class="empty">正在读取待应用模型…</div></div></article></section>
<section class="panel"><div class="headline"><div><h1>官方模型线路</h1><p>决定官方 GPT 的流量是否经过 OpenCodex。</p></div></div><article class="card gateway-card"><div class="settings-stack"><div class="setting" title="开启后，官方模型的流量由 OpenCodex 的路由代理接管：这是把 Codex 派生的子代理交给第三方模型的唯一方式，代价是 OpenCodex 出故障时官方模型会一起受影响。关闭后官方流量直连 ChatGPT，本项目的任何故障都影响不到它，但第三方模型无法作为子代理。改动后需重启 Codex Desktop。"><div><b>由路由代理接管官方模型流量</b><span id="native-egress-note">开启：第三方模型可作为子代理，但 OpenCodex 故障会影响官方模型 · 关闭：官方模型直连 ChatGPT，完全不受本项目影响</span></div><input id="native-egress-toggle" type="checkbox" checked style="width:20px;height:20px;accent-color:var(--green)" aria-label="由路由代理接管官方模型流量"></div><div class="setting" title="移除第三方模型和模型目录，同时注销 CODEX_CLI_PATH，让 Codex 完全回到原生状态。凭据保留。"><div><b>还原原生 Codex</b><span>移除第三方模型与托管配置，不改动 Computer Use / MCP。</span></div><button id="reset-button" class="button danger">还原原生</button></div></div></article></section>
<section class="panel"><div class="headline"><div><h1>日志</h1><p>网关与本机控制中心的运行记录；敏感凭据不会出现在这里。</p></div><button id="refresh-logs" class="button">刷新</button></div><article class="card gateway-card"><div id="log-list" class="log-list"><div class="empty">正在读取日志…</div></div></article></section>
</section></main>
<div id="provider-modal" class="modal"><form id="provider-form" class="modal-box"><h2 id="provider-modal-title">配置服务商</h2><p id="provider-modal-copy">预设地址与模型将自动使用。保存 Key 后模型会加入待应用清单，可在下方测试、保留或删除；重启 Codex 后才正式生效。</p><div class="form-grid"><label class="field wide">API Key<input id="provider-key" type="password" autocomplete="off" placeholder="保存后写入 macOS Keychain" required></label></div><div id="candidate-note" class="note hidden"></div><div class="modal-actions"><button type="button" id="close-modal" class="button">取消</button><button id="test-candidate" class="button primary" type="submit">保存并添加模型</button><button id="confirm-enable" class="button primary hidden" type="button">保存并添加模型</button></div></div><div id="toast" class="toast"></div>`;
